const constants={
    EMPTY_MALADES:'EMPTY_MALADES',
    SET_MALADES:'SET_MALADES',
    SET_RDVS:'SET_RDVS',
    REQUEST_MALADES:'REQUEST_MALADES',
    REQUEST_RDVS:'REQUEST_RDVS',
    RECEIVE_MALADES:'RECEIVE_MALADES',
    RECEIVE_RDVS:'RECEIVE_RDVS',
    SET_RDVM:'SET_RDVM',
    ADD_RDVM:'ADD_RDVM',
    DELETE_RDVM:'DELETE_RDVM',
    REQUEST_RDVM:'REQUEST_RDVM',
    RECEIVE_RDVM:'RECEIVE_RDVM',
    SET_RDVS_DATE:'SET_RDVS_DATE',
}

export default constants