const constants={
    SET_MALADES:'SET_MALADES',
    SET_RDVS:'SET_RDVS',
    REQUEST_MALADES:'REQUEST_MALADES',
    REQUEST_RDVS:'REQUEST_RDVS',
    RECEIVE_MALADES:'RECEIVE_MALADES',
    RECEIVE_RDVS:'RECEIVE_RDVS',
}

export default constants